name: drupal9-nginx
type: service
from: nginx-php
title: Nginx (Drupal 9)

update: auto
    
labels:
- drupal
- drupal9

settings:
- name: docroot
  title: Nginx docroot
  from: backend
  var: DOCROOT_SUBDIR

env:
- name: NGINX_VHOST_PRESET
  value: drupal9
