name: drupal9-nginx
type: service
title: Nginx (Drupal 9)
scalable: true

options:
- version: 1.19
  default: true
- version: 1.18

containers:
- name: nginx
  image: wodby/nginx
  env:
  - name: NGINX_VHOST_PRESET
    value: drupal9
  ports:
  - name: http
    number: 80
    type: http
    main: true
    
labels:
- nginx
- drupal
- drupal9

links:
- name: backend
  title: Backend
  env:
  - name: NGINX_BACKEND_HOST
    value: '{{link.host}}'
  - name: NGINX_BACKEND_PORT
    value: {{link.port}}
  selectors:
  - type: service
    labels:
    # both labels must match.
    - php-fpm
    - drupal
    # composer-like https://getcomposer.org/doc/articles/versions.md
    #option: ~7.1.0
# overrides.

build:
  dockerfile: Dockerfile

volumes:
- name: files
  from: backend
  title: Files
  path: /mnt/files

settings:
- name: docroot
  title: Nginx docroot
  from: backend
  var: DOCROOT_SUBDIR

env:
- name: NGINX_SERVER_ROOT
  value: /var/www/html/$(DOCROOT_SUBDIR)
