apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: nginx
  name: nginx
spec:
  selector:
    matchLabels:
      name: nginx
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - env:
        - name: NGINX_VHOST_PRESET
          value: drupal8
        - name: NGINX_SET_REAL_IP_FROM
          value: 172.17.0.0/16
        image: wodby/nginx
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - make
            - check-ready
            - -f
            - /usr/local/bin/actions.mk
          failureThreshold: 2
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 3
