name: drupal10-nginx
type: service
from: php-nginx
title: Nginx (Drupal 10)

update: auto
    
labels:
- drupal
- drupal10

volumes:
- name: files
  title: Files
  from: backend
  path: /mnt/files
  readOnly: true

settings:
- name: docroot
  title: Nginx docroot
  from: backend
  var: DOCROOT_SUBDIR
- name: sitedir
  title: Drupal site dir
  from: backend
  var: DRUPAL_SITE

configs:
- name: drupal10
  title: Drupal 10 preset
  filepath: /etc/gotpl/preset/drupal10.conf.tmpl
  config: drupal10.conf.tmpl

env:
- name: NGINX_VHOST_PRESET
  value: drupal10
