name: drupal10-nginx
type: service
from: php-nginx
title: Nginx (Drupal 10)

update: auto
    
labels:
- drupal
- drupal10

volumes:
- name: files
  title: Files
  from: backend
  path: /mnt/files
  readOnly: true

settings:
- name: docroot
  title: Nginx docroot
  from: backend
  var: DOCROOT_SUBDIR

env:
- name: NGINX_VHOST_PRESET
  value: drupal10
