name: drupal10-nginx
type: service
from: php-nginx
fromVersionConstraint: "^1.0.0"
fromVersion: "1.0.4"
title: Nginx (Drupal 10)


labels:
- drupal
- drupal10

build:
  dockerfile: Dockerfile

volumes:
- name: files
  title: Files
  from: backend
  path: /mnt/files
  readOnly: true

settings:
- name: docroot
  title: Nginx docroot
  from: backend
  var: DOCROOT_SUBDIR
  build: true
- name: sitedir
  title: Drupal site dir
  from: backend
  var: DRUPAL_SITE
  build: true

configs:
- name: drupal10
  title: Drupal 10 preset
  filepath: /etc/gotpl/preset/drupal10.conf.tmpl
  default:
    source: image
    filepath: /etc/gotpl/presets/drupal10.conf.tmpl

env:
- name: NGINX_VHOST_PRESET
  value: drupal10
