name: drupal8-nginx
type: service
title: Nginx (Drupal 8)
scalable: true

options:
- version: 1.17
  stability_tag: 5.6.10
  default: true
- version: 1.16
  stability_tag: 5.6.10
  
containers:
- name: nginx
  image: wodby/nginx
  env:
  - name: NGINX_BACKEND_HOST
    value: '{{links.backend.host}}'
  - name: NGINX_BACKEND_PORT
    value: '{{links.backend.port}}'
  - name: NGINX_VHOST_PRESET
    value: drupal8
  ports:
  - name: http
    number: 80
    type: http
    main: true
    
build:
- name: static
  from: php
  dockerfile: Dockerfile
    
labels:
- nginx
- drupal
- drupal8

links:
- name: backend
  title: Backend
  selectors:
  - type: service
    labels:
    # both labels must match.
    - php-fpm
    - drupal
    # composer-like https://getcomposer.org/doc/articles/versions.md
    #option: ~7.1.0
# overrides.

volumes:
- name: files
  from: backend
  title: Files
  path: /mnt/files

settings:
- name: docroot
  title: Nginx docroot
  from: backend
  var: DOCROOT_SUBDIR

env:
- name: NGINX_SERVER_ROOT
  value: /var/www/html/$(DOCROOT_SUBDIR)
